# -*- coding: utf-8 -*-
"""
Dados dos produtos da Varetas Brasil.
Fonte única usada por tools/gerar_paginas.py para gerar uma página por produto.
Para alterar um produto: edite aqui e rode  python3 tools/gerar_paginas.py
"""

POL = lambda *xs: [f'Ø {x}"' for x in xs]

PRODUTOS = [
    # ------------------------------------------------------------------ PONTEIRAS
    dict(
        slug="ponta-sem-fim-p4", cat="ponteiras", codigo="P4", img="ponteira-00.jpg",
        nome="Ponta Sem Fim (P4)",
        h1="Ponta Sem Fim para Vareta de Desentupimento",
        titulo="Ponta Sem Fim para Vareta de Desentupimento (P4)",
        resumo="Ponteira sem fim para varetas de desobstrução de esgoto, indicada para entupimentos com pano, estopa e papel.",
        indicada=["Entupimentos com pano", "Estopa", "Papel e materiais que se enrolam"],
        texto=[
            "A Ponta Sem Fim (P4) é uma das ponteiras mais usadas por quem trabalha com desobstrução de rede de esgoto. O formato em rosca sem fim prende e puxa materiais fibrosos como pano, estopa e papel, que costumam formar bolos difíceis de romper só com empurrão.",
            "Disponível em diâmetros de 1\" a 6\", ela acompanha desde ramais prediais até redes maiores. Encaixa nas varetas e engates Varetas Brasil.",
        ],
        tamanhos=POL("1", "1.1/2", "2", "2.1/2", "3", "3.1/2", "4", "6"),
        relacionados=["ponta-sem-fim-secao-chata-p14", "ponta-helicoidal-p6", "ponta-recuperadora-p5"],
    ),
    dict(
        slug="ponta-recuperadora-p5", cat="ponteiras", codigo="P5", img="ponteira-01.jpg",
        nome="Ponta Recuperadora de Varetas (P5)",
        h1="Ponta Recuperadora de Varetas e Cabos",
        titulo="Ponta Recuperadora de Varetas e Cabos (P5)",
        resumo="Ponteira para resgatar varetas e cabos que ficaram presos dentro da tubulação de esgoto.",
        indicada=["Vareta solta dentro da rede", "Cabo preso na tubulação", "Recuperação de ferramenta"],
        texto=[
            "Quando uma vareta desacopla ou um cabo fica preso dentro da rede, a Ponta Recuperadora (P5) é a ferramenta para buscá-lo de volta sem precisar abrir a tubulação.",
            "É item que todo profissional de desentupimento deveria ter na caminhonete: uma única recuperação já evita a perda do equipamento e horas de serviço parado.",
        ],
        tamanhos=[],
        relacionados=["chave-desacopladora-c8", "ponta-conica-para-cabos-c2", "kit-completo-de-varetas"],
    ),
    dict(
        slug="ponta-helicoidal-p6", cat="ponteiras", codigo="P6", img="ponteira-02.jpg",
        nome="Ponta Helicoidal (P6)",
        h1="Ponta Helicoidal para Desentupimento com Areia e Terra",
        titulo="Ponta Helicoidal para Vareta — Areia e Terra (P6)",
        resumo="Ponteira helicoidal para varetas de desobstrução, indicada para entupimentos com areia ou terra.",
        indicada=["Areia acumulada", "Terra na rede", "Sedimentos compactados"],
        texto=[
            "A Ponta Helicoidal (P6) foi projetada para redes obstruídas por areia ou terra. O formato helicoidal desagrega o material compactado e ajuda a abrir passagem ao longo da tubulação.",
            "Disponível de 1\" a 4\" de diâmetro, compatível com as varetas e engates Varetas Brasil.",
        ],
        tamanhos=POL("1", "1.1/2", "2", "2.1/2", "3", "3.1/2", "4"),
        relacionados=["ponta-seta-p11", "ponta-espada", "ponta-sem-fim-p4"],
    ),
    dict(
        slug="ponta-espiral-reta-ramais-p9", cat="ponteiras", codigo="P9", img="ponteira-03.jpg",
        nome="Ponta Espiral Reta para Ramais (P9)",
        h1="Ponta Espiral Reta para Desentupimento de Ramais",
        titulo="Ponta Espiral Reta para Ramais de Esgoto (P9)",
        resumo="Ponteira espiral reta para o início do desentupimento de ramais, nos comprimentos 500, 1000 e 1500 mm.",
        indicada=["Início do desentupimento", "Ramais prediais", "Abertura de passagem"],
        texto=[
            "A Ponta Espiral Reta para Ramais (P9) é usada no começo do serviço, para abrir a primeira passagem na obstrução antes de entrar com ponteiras de maior diâmetro.",
            "Disponível nos comprimentos de 500, 1000 e 1500 mm.",
        ],
        tamanhos=["500 mm", "1000 mm", "1500 mm"],
        relacionados=["ponta-espiral-reta-varetas", "ponta-espada", "ponta-sem-fim-p4"],
    ),
    dict(
        slug="ponta-limpeza-tubulacao-p10", cat="ponteiras", codigo="P10", img="ponteira-04.jpg",
        nome="Ponta Limpeza de Tubulação d'Água (P10)",
        h1="Ponta para Limpeza de Tubulação — Materiais Pastosos",
        titulo="Ponta para Limpeza de Tubulação d'Água (P10)",
        resumo="Ponteira para desobstrução de materiais pastosos e limpeza de tubulação, de 2\" a 3.1/2\".",
        indicada=["Materiais pastosos", "Limpeza de tubulação", "Resíduos aderidos"],
        texto=[
            "A Ponta Limpeza de Tubulação (P10) atua em obstruções de material pastoso, que não se rompem com pontas de corte e precisam ser arrastadas para liberar a tubulação.",
            "Disponível de 2\" a 3.1/2\" de diâmetro.",
        ],
        tamanhos=POL("2", "2.1/2", "3", "3.1/2"),
        relacionados=["ponta-seta-p11", "ponta-4-laminas-gordura-p13", "ponta-cortadora"],
    ),
    dict(
        slug="ponta-seta-p11", cat="ponteiras", codigo="P11", img="ponteira-05.jpg",
        nome="Ponta Seta (P11)",
        h1="Ponta Seta para Vareta de Desobstrução",
        titulo="Ponta Seta para Vareta de Desobstrução (P11)",
        resumo="Ponteira seta para areia, terra, material pastoso e fibroso, de 2\" a 3.1/2\".",
        indicada=["Areia e terra", "Material pastoso", "Material fibroso"],
        texto=[
            "A Ponta Seta (P11) é uma ponteira versátil: atende areia, terra, material pastoso e fibroso. É uma boa escolha quando o tipo de obstrução ainda não está claro.",
            "Disponível de 2\" a 3.1/2\" de diâmetro.",
        ],
        tamanhos=POL("2", "2.1/2", "3", "3.1/2"),
        relacionados=["ponta-helicoidal-p6", "ponta-limpeza-tubulacao-p10", "ponta-espada"],
    ),
    dict(
        slug="ponta-4-laminas-dentada-p12", cat="ponteiras", codigo="P12", img="ponteira-06.jpg",
        nome="Ponta 4 Lâminas Dentada (P12)",
        h1="Ponta 4 Lâminas Dentada para Rede de Esgoto",
        titulo="Ponta 4 Lâminas Dentada para Vareta (P12)",
        resumo="Ponteira de 4 lâminas dentadas para desobstrução e corte na rede de esgoto, de 2\" a 3.1/2\".",
        indicada=["Corte de obstruções", "Rede de esgoto", "Bloqueios resistentes"],
        texto=[
            "A Ponta 4 Lâminas Dentada (P12) combina desobstrução e corte. As lâminas dentadas atacam bloqueios mais resistentes dentro da rede de esgoto.",
            "Disponível de 2\" a 3.1/2\" de diâmetro.",
        ],
        tamanhos=POL("2", "2.1/2", "3", "3.1/2"),
        relacionados=["ponta-4-laminas-gordura-p13", "ponta-serra-copo-raizes-p1", "ponta-cortadora"],
    ),
    dict(
        slug="ponta-4-laminas-gordura-p13", cat="ponteiras", codigo="P13", img="ponteira-07.jpg",
        nome="Ponta 4 Lâminas para Gordura (P13)",
        h1="Ponta 4 Lâminas para Desentupimento de Gordura",
        titulo="Ponta 4 Lâminas para Gordura em Esgoto (P13)",
        resumo="Ponteira de 4 lâminas para desobstrução de rede de esgoto com gordura, de 2\" a 3.1/2\".",
        indicada=["Gordura acumulada", "Redes de cozinhas e restaurantes", "Rede de esgoto"],
        texto=[
            "A Ponta 4 Lâminas para Gordura (P13) é indicada para redes de esgoto obstruídas por gordura, um problema comum em redes que recebem efluente de cozinhas, restaurantes e condomínios.",
            "Disponível de 2\" a 3.1/2\" de diâmetro.",
        ],
        tamanhos=POL("2", "2.1/2", "3", "3.1/2"),
        relacionados=["ponta-cortadora", "ponta-4-laminas-dentada-p12", "ponta-limpeza-tubulacao-p10"],
    ),
    dict(
        slug="ponta-sem-fim-secao-chata-p14", cat="ponteiras", codigo="P14", img="ponteira-08.jpg",
        nome="Ponta Sem Fim Seção Chata (P14)",
        h1="Ponta Sem Fim Seção Chata para Entupimentos Críticos",
        titulo="Ponta Sem Fim Seção Chata — Entupimentos Críticos (P14)",
        resumo="Ponteira sem fim de seção chata para entupimentos críticos com pano, folhas, estopa e madeira, de 3\" a 4\".",
        indicada=["Pano e estopa", "Folhas", "Pedaços de madeira"],
        texto=[
            "A Ponta Sem Fim Seção Chata (P14) é a versão reforçada da ponta sem fim, feita para entupimentos críticos com pano, folhas, estopa e até pedaços de madeira.",
            "Disponível em 3\", 3.1/2\" e 4\" de diâmetro, para redes maiores.",
        ],
        tamanhos=POL("3", "3.1/2", "4"),
        relacionados=["ponta-sem-fim-p4", "ponta-serra-copo-raizes-p1", "ponta-recuperadora-p5"],
    ),
    dict(
        slug="ponta-serra-copo-raizes-p1", cat="ponteiras", codigo="P1", img="ponteira-09.jpg",
        nome="Ponta Serra Copo para Raízes (P1)",
        h1="Ponta Serra Copo para Raízes na Rede de Esgoto",
        titulo="Ponta Serra Copo para Raízes em Esgoto (P1)",
        resumo="Ponteira serra copo para entupimentos causados por raízes na rede de esgoto, de 2\" a 4\".",
        indicada=["Raízes dentro da tubulação", "Redes próximas a árvores", "Calçadas e áreas verdes"],
        texto=[
            "Raízes que entram pelas juntas da tubulação são uma das causas mais comuns de entupimento recorrente em redes públicas e condomínios. A Ponta Serra Copo (P1) corta as raízes e libera o diâmetro da rede.",
            "Disponível de 2\" a 4\" de diâmetro.",
        ],
        tamanhos=POL("2", "2.1/2", "3", "3.1/2", "4"),
        relacionados=["ponta-4-laminas-dentada-p12", "ponta-sem-fim-secao-chata-p14", "ponta-cortadora"],
    ),
    dict(
        slug="ponta-espiral-reta-cabos-c3", cat="ponteiras", codigo="C3", img="ponteira-10.jpg",
        nome="Ponta Espiral Reta para Cabos (C3)",
        h1="Ponta Espiral Reta para Cabos de Desentupimento",
        titulo="Ponta Espiral Reta para Cabos de Desentupimento (C3)",
        resumo="Ponteira espiral reta para cabos, para o início do desentupimento e uso geral, Ø 1.1/4\" em 200, 300 e 500 mm.",
        indicada=["Início do desentupimento", "Uso geral", "Cabos espirais"],
        texto=[
            "A Ponta Espiral Reta para Cabos (C3) abre a primeira passagem na obstrução e serve para uso geral com cabos de desentupimento.",
            "Diâmetro de 1.1/4\", nos comprimentos de 200, 300 e 500 mm.",
        ],
        tamanhos=['Ø 1.1/4" × 200 mm', 'Ø 1.1/4" × 300 mm', 'Ø 1.1/4" × 500 mm'],
        relacionados=["cabo-espiral", "ponta-conica-para-cabos-c2", "adaptador-cabos-varetas"],
    ),
    dict(
        slug="ponta-conica-para-cabos-c2", cat="ponteiras", codigo="C2", img="ponteira-11.jpg",
        nome="Ponta Cônica para Cabos (C2)",
        h1="Ponta Cônica para Recuperação de Cabos",
        titulo="Ponta Cônica para Recuperação de Cabos (C2)",
        resumo="Ponteira cônica para recuperar cabos dentro da tubulação, Ø 1.1/4\" em 200 e 300 mm.",
        indicada=["Cabo preso na tubulação", "Recuperação de equipamento"],
        texto=[
            "A Ponta Cônica (C2) é usada para recuperar cabos que ficaram dentro da tubulação, evitando a perda do equipamento.",
            "Diâmetro de 1.1/4\", nos comprimentos de 200 e 300 mm.",
        ],
        tamanhos=['Ø 1.1/4" × 200 mm', 'Ø 1.1/4" × 300 mm'],
        relacionados=["ponta-recuperadora-p5", "cabo-espiral", "ponta-espiral-reta-cabos-c3"],
    ),
    dict(
        slug="cabo-espiral", cat="ponteiras", codigo="", img="ponteira-12.jpg",
        nome="Cabo Espiral para Desobstrução",
        h1="Cabo Espiral para Desentupimento de Esgoto",
        titulo="Cabo Espiral para Desentupimento de Esgoto 1.1/4\"",
        resumo="Cabo espiral para uso geral em rede de esgoto, Ø 1.1/4\" com 4,57 m.",
        indicada=["Uso geral em rede de esgoto", "Complemento às varetas"],
        texto=[
            "O Cabo Espiral é usado em desobstrução geral de redes de esgoto. Com o Adaptador para Cabos e Varetas, ele trabalha em conjunto com o sistema de varetas.",
            "Diâmetro de 1.1/4\" e 4,57 m de comprimento.",
        ],
        tamanhos=[],
        relacionados=["adaptador-cabos-varetas", "ponta-espiral-reta-cabos-c3", "ponta-conica-para-cabos-c2"],
    ),
    dict(
        slug="ponta-cortadora", cat="ponteiras", codigo="", img="ponteira-13.jpg",
        nome="Ponta Cortadora para Cabos e Varetas",
        h1="Ponta Cortadora para Gordura em Esgoto",
        titulo="Ponta Cortadora para Cabos e Varetas — Gordura",
        resumo="Ponteira cortadora para cabos e varetas, indicada para desobstrução de gordura em esgotos, de 2\" a 3.1/2\".",
        indicada=["Gordura em esgoto", "Uso com cabos ou varetas"],
        texto=[
            "A Ponta Cortadora serve tanto para cabos quanto para varetas e é indicada para desobstrução de gordura em redes de esgoto.",
            "Disponível de 2\" a 3.1/2\" de diâmetro.",
        ],
        tamanhos=POL("2", "2.1/2", "3", "3.1/2"),
        relacionados=["ponta-4-laminas-gordura-p13", "ponta-4-laminas-dentada-p12", "ponta-limpeza-tubulacao-p10"],
    ),
    dict(
        slug="ponta-espada", cat="ponteiras", codigo="", img="ponteira-14.jpg",
        nome="Ponta Espada",
        h1="Ponta Espada para Tubulação Obstruída por Barro",
        titulo="Ponta Espada para Vareta — Barro na Tubulação",
        resumo="Ponteira espada para tubulações obstruídas por barro, usada após as pontas retas, de 2\" a 3.1/2\".",
        indicada=["Barro na tubulação", "Segunda etapa após pontas retas"],
        texto=[
            "A Ponta Espada é indicada para tubulações obstruídas por barro. Normalmente entra depois das pontas espirais retas, que abrem a primeira passagem.",
            "Disponível de 2\" a 3.1/2\" de diâmetro.",
        ],
        tamanhos=POL("2", "2.1/2", "3", "3.1/2"),
        relacionados=["ponta-espiral-reta-varetas", "ponta-helicoidal-p6", "ponta-seta-p11"],
    ),
    dict(
        slug="ponta-espiral-reta-varetas", cat="ponteiras", codigo="", img="ponteira-15.jpg",
        nome="Ponta Espiral Reta para Varetas",
        h1="Ponta Espiral Reta para Varetas de Desentupimento",
        titulo="Ponta Espiral Reta para Varetas de Desentupimento",
        resumo="Ponteira espiral reta para varetas, para o início do desentupimento e uso geral, Ø 1.1/4\" em 200, 300 e 500 mm.",
        indicada=["Início do desentupimento", "Uso geral com varetas"],
        texto=[
            "A Ponta Espiral Reta para Varetas é a ponteira de abertura: entra primeiro na obstrução para criar passagem antes das pontas de maior diâmetro.",
            "Diâmetro de 1.1/4\", nos comprimentos de 200, 300 e 500 mm.",
        ],
        tamanhos=['Ø 1.1/4" × 200 mm', 'Ø 1.1/4" × 300 mm', 'Ø 1.1/4" × 500 mm'],
        relacionados=["ponta-espiral-reta-ramais-p9", "ponta-espada", "ponta-sem-fim-p4"],
    ),
    # ------------------------------------------------------------------ ACESSÓRIOS
    dict(
        slug="engate-tipo-t-em2", cat="acessorios", codigo="EM2", img="acessorio-00.jpg",
        nome="Engate Tipo-T para Varetas (EM2)",
        h1="Engate Tipo T para Varetas de Desobstrução",
        titulo="Engate Tipo T para Varetas de Desobstrução (EM2)",
        resumo="Engate tipo T macho e fêmea para varetas de desobstrução, Ø 7/8\", em aço 1045 temperado e revenido.",
        indicada=["Reposição de engates", "Montagem de varetas", "Manutenção da frota"],
        texto=[
            "O Engate Tipo-T (EM2) é o engate usado nas varetas Varetas Brasil. Vendido nas versões macho e fêmea, serve para reposição e manutenção das varetas.",
            "Fabricado em aço 1045 temperado e revenido, com Ø 7/8\".",
        ],
        tamanhos=["Macho", "Fêmea"],
        relacionados=["engate-roscado-sewer-rodder", "chave-desacopladora-c8", "acionador-manual-manivela-a7"],
    ),
    dict(
        slug="engate-roscado-sewer-rodder", cat="acessorios", codigo="", img="acessorio-01.jpg",
        nome="Engate Roscado Sewer Rodder — Castanha",
        h1="Engate Roscado Sewer Rodder (Castanha)",
        titulo="Engate Roscado Sewer Rodder — Castanha 7/8\"",
        resumo="Engate roscado padrão sewer rodder (castanha), macho e fêmea, Ø 7/8\", em aço 1045 temperado e revenido.",
        indicada=["Varetas com engate roscado", "Reposição de castanha", "Equipamentos sewer rodder"],
        texto=[
            "O Engate Roscado Sewer Rodder, conhecido como castanha, atende varetas com conexão roscada. Vendido nas versões macho e fêmea.",
            "Fabricado em aço 1045 temperado e revenido, com Ø 7/8\".",
        ],
        tamanhos=["Macho", "Fêmea"],
        relacionados=["engate-tipo-t-em2", "adaptador-cabos-varetas", "chave-desacopladora-c8"],
    ),
    dict(
        slug="chave-desacopladora-c8", cat="acessorios", codigo="C8", img="acessorio-02.jpg",
        nome="Chave Desacopladora de Varetas (C8)",
        h1="Chave Desacopladora de Varetas",
        titulo="Chave Desacopladora de Varetas de Desentupimento (C8)",
        resumo="Chave para desacoplar varetas de desobstrução, em aço carbono 1045.",
        indicada=["Desmontagem das varetas", "Troca de ponteiras"],
        texto=[
            "A Chave Desacopladora (C8) separa as varetas com rapidez e segurança ao fim do serviço ou na troca de ponteiras.",
            "Fabricada em aço carbono 1045.",
        ],
        tamanhos=[],
        relacionados=["engate-tipo-t-em2", "acionador-manual-manivela-a7", "ponta-recuperadora-p5"],
    ),
    dict(
        slug="adaptador-cabos-varetas", cat="acessorios", codigo="", img="acessorio-03.jpg",
        nome="Adaptador para Cabos e Varetas",
        h1="Adaptador para Cabos e Varetas de Desentupimento",
        titulo="Adaptador para Cabos e Varetas de Desentupimento",
        resumo="Adaptador que une o engate macho de varetas ao engate fêmea de cabos.",
        indicada=["Usar cabos com o sistema de varetas", "Ampliar o alcance do conjunto"],
        texto=[
            "O Adaptador une o engate macho das varetas ao engate fêmea dos cabos, permitindo usar os dois equipamentos no mesmo serviço.",
        ],
        tamanhos=[],
        relacionados=["cabo-espiral", "engate-tipo-t-em2", "ponta-espiral-reta-cabos-c3"],
    ),
    dict(
        slug="acionador-manual-manivela-a7", cat="acessorios", codigo="A7", img="acessorio-04.jpg",
        nome="Acionador Manual — Manivela (A7)",
        h1="Acionador Manual (Manivela) para Varetas",
        titulo="Acionador Manual — Manivela para Varetas (A7)",
        resumo="Acionador manual tipo manivela para uso geral em varetas de desobstrução, em aço carbono 1045.",
        indicada=["Girar o conjunto de varetas", "Uso geral"],
        texto=[
            "O Acionador Manual (A7) é a manivela que gira o conjunto de varetas durante o desentupimento, dando torque para as ponteiras trabalharem na obstrução.",
            "Fabricado em aço carbono 1045.",
        ],
        tamanhos=[],
        relacionados=["chave-desacopladora-c8", "kit-completo-de-varetas", "engate-tipo-t-em2"],
    ),
    # ------------------------------------------------------------------ KITS
    dict(
        slug="kit-completo-de-varetas", cat="kit", codigo="", img="kit-00.jpg",
        nome="Kit Completo de Varetas",
        h1="Kit Completo de Varetas para Desentupimento de Esgoto",
        titulo="Kit de Varetas para Desentupimento — 25 Varetas de 2 m",
        resumo="Kit com 25 varetas de 2 m em aço cromo-silício, acionador manual, ponta recuperadora, ponta sem fim, ponta helicoidal e chave desacopladora.",
        indicada=["Quem está montando a equipe", "Frotas de prefeituras e SAAEs", "Desentupidoras"],
        texto=[
            "O Kit Completo reúne o necessário para começar a trabalhar com varetas: 25 varetas de 2 m em aço cromo-silício (50 m de alcance), acionador manual, chave desacopladora e três ponteiras (recuperadora, sem fim e helicoidal).",
            "É a forma mais simples de equipar uma nova equipe ou um novo veículo de uma só vez.",
        ],
        tamanhos=[],
        relacionados=["kit-acessorios-varetas", "ponta-sem-fim-p4", "ponta-helicoidal-p6"],
    ),
    dict(
        slug="kit-acessorios-varetas", cat="kit", codigo="", img="kit-01.jpg",
        nome="Kit Acessórios para Uso em Varetas",
        h1="Kit de Ponteiras e Acessórios para Varetas",
        titulo="Kit de Ponteiras e Acessórios para Varetas de 3\"",
        resumo="Kit com acionador, chave e ponteiras de 3\": recuperadora, helicoidal, sem fim, 4 lâminas (gordura e dentada), limpeza de tubulação e seta.",
        indicada=["Quem já tem varetas", "Completar o jogo de ponteiras"],
        texto=[
            "Para quem já tem varetas, o Kit Acessórios reúne acionador, chave e sete ponteiras de 3\": recuperadora, helicoidal, sem fim, 4 lâminas para gordura, 4 lâminas dentada, limpeza de tubulação e seta.",
            "Cobre os tipos de obstrução mais comuns em rede de esgoto com um único pedido.",
        ],
        tamanhos=[],
        relacionados=["kit-completo-de-varetas", "ponta-4-laminas-gordura-p13", "ponta-seta-p11"],
    ),
]

CATEGORIAS = {
    "ponteiras": ("Ponteiras", "ponteiras.html"),
    "acessorios": ("Acessórios", "acessorios.html"),
    "kit": ("Kit Completo", "kit-completo.html"),
}

# Nome do item no catálogo existente -> slug (para ligar o catálogo à página do produto)
POR_NOME = {p["nome"]: p["slug"] for p in PRODUTOS}
